version: '0.0.1.{build}'

image: Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

build:
  project: SpaceGameEngine.sln

test_script:
  - pwsh ./run_test_on_appveyor.ps1