trigger:
  - master

pool:
  vmImage: 'macos-latest'

jobs:
  - job: 'MacOS_Debug'
    steps:
      - template: cmake-template.yml
        parameters:
          buildType: Debug
  - job: 'MacOS_Release'
    steps:
      - template: cmake-template.yml
        parameters:
          buildType: Release
  - job: 'MacOS_RelWithDebInfo'
    steps:
      - template: cmake-template.yml
        parameters:
          buildType: RelWithDebInfo
  - job: 'MacOS_MinSizeRel'
    steps:
      - template: cmake-template.yml
        parameters:
          buildType: MinSizeRel