trigger:
  - master

pool:
  vmImage: 'macos-latest'

steps:
  - task: Bash@3
    displayName: 'setup third-party dependencies'
    inputs:
      filePath: 'setup.sh'

  - script: |
      mkdir build
      cd build
      cmake ..
      make -j4
    displayName: 'build'

  - task: Bash@3
    displayName: 'run tests'
    inputs:
      filePath: 'azure-pipelines/run-tests.sh'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '*-REPORT.xml'
      failTaskOnFailedTests: true