trigger:
  - master

pool:
  vmImage: 'macos-latest'

steps:
  - task: Bash@3
    displayName: 'setup third-party dependencies'
    inputs:
      filePath: 'setup.sh'

  - script: |
      mkdir build
      cd build
      cmake ..
      make -j4
    displayName: 'build'

  - script: |
      build/Test/TestCatch2/TestCatch2 -r junit -o TEST-Catch2.xml
      build/Test/TestCommon/TestCommon -r junit -o TEST-Common.xml
    displayName: 'test'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'TEST-*.xml'
      failTaskOnFailedTests: true