pool:
    vmImage: "macos-latest"

jobs:
    - job: "MacOS_Debug"
      steps:
          - template: cmake-template.yml
            parameters:
                toolchain: CC=$(brew --prefix llvm@14)/bin/clang CXX=$(brew --prefix llvm)/bin/clang++
                buildType: Debug
    - job: "MacOS_Release"
      steps:
          - template: cmake-template.yml
            parameters:
                toolchain: CC=$(brew --prefix llvm@14)/bin/clang CXX=$(brew --prefix llvm)/bin/clang++
                buildType: Release
    - job: "MacOS_RelWithDebInfo"
      steps:
          - template: cmake-template.yml
            parameters:
                toolchain: CC=$(brew --prefix llvm@14)/bin/clang CXX=$(brew --prefix llvm)/bin/clang++
                buildType: RelWithDebInfo
    - job: "MacOS_MinSizeRel"
      steps:
          - template: cmake-template.yml
            parameters:
                toolchain: CC=$(brew --prefix llvm@14)/bin/clang CXX=$(brew --prefix llvm)/bin/clang++
                buildType: MinSizeRel
