trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      sudo apt-get update
      sudo apt-get install gcc-9 g++-9
      gcc-9 --version
      g++-9 --version
    displayName: 'upgrade gcc'

  - task: Bash@3
    displayName: 'setup third-party dependencies'
    inputs:
      filePath: 'setup.sh'

  - script: |
      mkdir build
      cd build
      CC=gcc-9 CXX=g++-9 cmake ..
      make -j4
    displayName: 'build'

  - task: Bash@3
    displayName: 'run tests'
    inputs:
      filePath: 'azure-pipelines/run-tests.sh'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'TEST-*.xml'
      failTaskOnFailedTests: true