trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: 'Ubuntu_Debug'
    steps:
      - task: Bash@3
          displayName: 'Setup GCC'
          inputs:
            filePath: 'azure-pipelines/setup-gcc9.sh'
      - template: cmake-template.yml
        parameters:
          toolchain: CC=gcc-9 CXX=g++-9
          buildType: Debug
  - job: 'Ubuntu_Release'
    steps:
      - task: Bash@3
          displayName: 'Setup GCC'
          inputs:
            filePath: 'azure-pipelines/setup-gcc9.sh'
      - template: cmake-template.yml
        parameters:
          toolchain: CC=gcc-9 CXX=g++-9
          buildType: Release
  - job: 'Ubuntu_RelWithDebInfo'
    steps:
      - task: Bash@3
          displayName: 'Setup GCC'
          inputs:
            filePath: 'azure-pipelines/setup-gcc9.sh'
      - template: cmake-template.yml
        parameters:
          toolchain: CC=gcc-9 CXX=g++-9
          buildType: RelWithDebInfo
  - job: 'Ubuntu_MinSizeRel'
    steps:
      - task: Bash@3
          displayName: 'Setup GCC'
          inputs:
            filePath: 'azure-pipelines/setup-gcc9.sh'
      - template: cmake-template.yml
        parameters:
          toolchain: CC=gcc-9 CXX=g++-9
          buildType: MinSizeRel