pool:
  vmImage: 'ubuntu-22.04'

jobs:
  - job: 'Ubuntu_Debug'
    steps:
      - template: cmake-template.yml
        parameters:
          toolchain: CC=gcc-11 CXX=g++-11
          buildType: Debug
  - job: 'Ubuntu_Release'
    steps:
      - template: cmake-template.yml
        parameters:
          toolchain: CC=gcc-11 CXX=g++-11
          buildType: Release
  - job: 'Ubuntu_RelWithDebInfo'
    steps:
      - template: cmake-template.yml
        parameters:
          toolchain: CC=gcc-11 CXX=g++-11
          buildType: RelWithDebInfo
  - job: 'Ubuntu_MinSizeRel'
    steps:
      - template: cmake-template.yml
        parameters:
          toolchain: CC=gcc-11 CXX=g++-11
          buildType: MinSizeRel