trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
  - task: MSBuild@1
    displayName: 'build'
    inputs:
      solution: 'SpaceGameEngine.sln'
      maximumCpuCount: true
      msbuildArchitecture: 'x64'

  - script: |
      Binary\TestCatch2\x64\Debug\TestCatch2.exe -r junit -o TEST-Catch2.xml
      Binary\TestCommon\x64\Debug\TestCommon.exe -r junit -o TEST-Common.xml
    displayName: 'test'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'
      failTaskOnFailedTests: true