jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: PowerShell@2
    displayName: 'Setup third-party dependencies'
    inputs:
      filePath: 'setup.ps1'
  - task: VSBuild@1
    displayName: 'Build'
    inputs:
      solution: 'SpaceGameEngine.sln'
      maximumCpuCount: true
      configuration: ${{ parameters.msbuildConfig }}
      platform: ${{ parameters.msbuildArch }}
  - task: PowerShell@2
    displayName: 'Test'
    inputs:
      filePath: 'azure-pipelines/run-tests.ps1'
      arguments: ${{ parameters.msbuildArch }} ${{ parameters.msbuildConfig }}
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*-REPORT.xml'
      failTaskOnFailedTests: true
