jobs:
  - template: windows-template.yml
    parameters:
      name: 'VS2019_x86_Debug'
      vmImage: 'windows-2019'
      msbuildArch: 'x86'
      msbuildConfig: 'Debug'

  - template: windows-template.yml
    parameters:
      name: 'VS2019_x64_Debug'
      vmImage: 'windows-2019'
      msbuildArch: 'x64'
      msbuildConfig: 'Debug'

  - template: windows-template.yml
    parameters:
      name: 'VS2019_x86_Release'
      vmImage: 'windows-2019'
      msbuildArch: 'x86'
      msbuildConfig: 'Release'

  - template: windows-template.yml
    parameters:
      name: 'VS2019_x64_Release'
      vmImage: 'windows-2019'
      msbuildArch: 'x64'
      msbuildConfig: 'Release'

  - template: windows-template.yml
    parameters:
      name: 'VS2022_x86_Debug'
      vmImage: 'windows-2022'
      msbuildArch: 'x86'
      msbuildConfig: 'Debug'

  - template: windows-template.yml
    parameters:
      name: 'VS2022_x64_Debug'
      vmImage: 'windows-2022'
      msbuildArch: 'x64'
      msbuildConfig: 'Debug'

  - template: windows-template.yml
    parameters:
      name: 'VS2022_x86_Release'
      vmImage: 'windows-2022'
      msbuildArch: 'x86'
      msbuildConfig: 'Release'

  - template: windows-template.yml
    parameters:
      name: 'VS2022_x64_Release'
      vmImage: 'windows-2022'
      msbuildArch: 'x64'
      msbuildConfig: 'Release'
